'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, BriefcaseBusiness, Check, Clipboard, FileText, History, LoaderCircle, ShieldAlert, Sparkles, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Analysis } from '@/lib/analyzer';

type Item={id:string;createdAt:number;result:Analysis};
const exampleJd=`AI 应用开发助理｜上海\n岗位职责：参与 AI 工具和自动化工作流搭建，完成前端页面与 API 对接。\n任职要求：熟悉 JavaScript / TypeScript，能使用 React 完成页面开发。\n熟悉 Git 和 GitHub，能说明自己的项目并提供代码。\n能够阅读需求，独立调试并部署可访问的 Demo。\n了解 Python、SQL 或 Agent 工作流优先。\n有清晰的沟通与文档习惯。`;
const exampleProfile=`我有独立完成并部署网页项目的实践，使用 Codex 辅助开发、调试和整理 README。\n项目：Pixel Flow AI Console，Live Demo：https://pixel-flow-ai-console.vercel.app\nGitHub：https://github.com/wuchan1870422-byte/pixel-flow-ai-console\n我能展示页面、说明实际由我完成的步骤和遇到的问题。`;
const labels={must:'必须条件',bonus:'加分项',stack:'技术要求',risk:'需核实'};
export default function Home(){
 const [jd,setJd]=useState(''),[profile,setProfile]=useState(''),[item,setItem]=useState<Item|null>(null),[history,setHistory]=useState<Item[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[showHistory,setShowHistory]=useState(false),[canSave,setCanSave]=useState(false);
 useEffect(()=>{fetch('/api/analyses').then(async r=>r.ok?await r.json() as {items:Item[];saved:boolean}:null).then(d=>{if(d?.items)setHistory(d.items);setCanSave(!!d?.saved)}).catch(()=>{})},[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'analyze_job_posting',title:'分析招聘岗位',description:'分析给定岗位 JD 与真实经历，保存并显示匹配证据、缺口和求职准备建议。',inputSchema:{type:'object',properties:{jd:{type:'string',minLength:20},profile:{type:'string',minLength:15}},required:['jd','profile'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){const v=input as {jd?:unknown;profile?:unknown};if(typeof v?.jd!=='string'||typeof v?.profile!=='string'||v.jd.trim().length<20||v.profile.trim().length<15)throw new Error('需要至少 20 字 JD 和 15 字个人资料');const response=await fetch('/api/analyses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jd:v.jd,profile:v.profile})});const data=await response.json() as {error?:string;item:Item;saved?:boolean};if(!response.ok)throw new Error(data.error||'分析失败');setJd(v.jd);setProfile(v.profile);setItem(data.item);if(data.saved)setHistory(p=>[data.item,...p].slice(0,30));return {id:data.item.id,title:data.item.result.title,score:data.item.result.score,verdict:data.item.result.verdict}}},{signal:controller.signal})).catch(()=>{});}catch{}
  return()=>controller.abort();
 },[]);
 async function run(){if(jd.trim().length<20||profile.trim().length<15){setError('请先填写至少 20 字的 JD 和至少 15 字的个人资料。');return}setBusy(true);setError('');try{const r=await fetch('/api/analyses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jd,profile})});const d=await r.json() as {error?:string;item:Item;saved?:boolean};if(!r.ok)throw new Error(d.error||'分析失败');setItem(d.item);if(d.saved)setHistory(p=>[d.item,...p].slice(0,30));setTimeout(()=>document.getElementById('result')?.scrollIntoView({behavior:'smooth'}),60)}catch(e){setError(e instanceof Error?e.message:'分析失败，请重试。')}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm('删除这条分析记录？'))return;try{const r=await fetch('/api/analyses?id='+encodeURIComponent(id),{method:'DELETE'});if(!r.ok)throw new Error();setHistory(p=>p.filter(x=>x.id!==id));if(item?.id===id)setItem(null)}catch{setError('删除失败，请稍后重试。')}}
 async function copy(){if(!item)return;try{await navigator.clipboard.writeText(item.result.opener);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('复制失败，请手动选择文本。')}}
 const a=item?.result;
 return <main><header className="top"><div className="brand"><span className="logo"><BriefcaseBusiness size={20}/></span><div><strong>JobHunter <em>Agent</em></strong><small>JOB INTELLIGENCE WORKSPACE</small></div></div><span className="top-status">● 项目二 · 可交互演示</span></header><div className="layout"><aside><div className="side-label">工作台</div><a className="nav selected" href="#workspace"><FileText size={17}/>岗位分析</a><button className="nav" onClick={()=>setShowHistory(!showHistory)}><History size={17}/>历史记录 <span>{history.length}</span></button><hr/><div className="side-label">使用流程</div><p className="step">01　粘贴目标岗位 JD</p><p className="step">02　填写真实经历和作品</p><p className="step">03　核对分析并编辑话术</p><div className="side-note"><ShieldAlert size={17}/><span>请勿上传身份证、电话等敏感信息。{canSave?"历史记录仅自己可见。":"访客可试用，记录不保存。"}</span></div></aside><div className="content" id="workspace"><div className="intro"><div className="kicker">APPLICATION / 01</div><h1>岗位匹配分析</h1><p>把招聘要求和你的真实经历放在一起，找到能证明的优势与需要补足的部分。</p></div>
 {showHistory&&<section className="panel history"><div className="section-head"><div><h2>历史记录</h2><p>最近保存的 30 次分析</p></div><Button variant="ghost" size="sm" onClick={()=>setShowHistory(false)}>收起</Button></div>{history.length?history.map(h=><div className="history-row" key={h.id}><button onClick={()=>{setItem(h);setShowHistory(false);setTimeout(()=>document.getElementById('result')?.scrollIntoView({behavior:'smooth'}),50)}}><strong>{h.result.title}</strong><small>{new Date(h.createdAt).toLocaleString('zh-CN')} · 覆盖 {h.result.score}%</small></button><Button variant="ghost" size="icon" aria-label={'删除'+h.result.title} onClick={()=>remove(h.id)}><Trash2 size={16}/></Button></div>):<p className="muted">还没有记录。登录访问后完成分析会自动保存；访客分析不保存。</p>}</section>}
 <div className="inputs"><section className="panel input-panel"><div className="input-head"><b>01</b><div><h2>招聘岗位 JD</h2><p>粘贴岗位职责和任职要求</p></div></div><textarea aria-label="招聘岗位 JD" value={jd} onChange={e=>setJd(e.target.value)} maxLength={15000} placeholder="例如：岗位职责、学历要求、经验要求、技术栈、加分项……"/><div className="input-foot"><span>{jd.length} / 15,000 字</span><button onClick={()=>setJd(exampleJd)}>填入示例 JD <ArrowRight size={14}/></button></div></section><section className="panel input-panel"><div className="input-head"><b className="cyan">02</b><div><h2>我的经历 / 项目</h2><p>只填写确实做过的内容</p></div></div><textarea aria-label="个人经历和项目" value={profile} onChange={e=>setProfile(e.target.value)} maxLength={10000} placeholder="例如：项目做了什么、使用过的工具、可展示的 GitHub 和在线作品、相关技能……"/><div className="input-foot"><span>{profile.length} / 10,000 字</span><button onClick={()=>setProfile(exampleProfile)}>填入示例资料 <ArrowRight size={14}/></button></div></section></div>
 <div className="actions"><span><ShieldAlert size={16}/> AI 可检索资料和公开 GitHub；结果需人工核对。</span><Button onClick={run} disabled={busy} className="run">{busy?<LoaderCircle size={17} className="spin"/>:<Sparkles size={17}/>} {busy?'正在分析…':'分析岗位匹配'} <ArrowRight size={17}/></Button></div>{error&&<p className="error" role="alert">{error}</p>}
 {!a&&<div className="empty"><span><FileText size={24}/></span><div><strong>从一份真实 JD 开始</strong><p>完成分析后，这里会显示逐条要求、匹配依据、开场白和面试准备。</p></div></div>}
 {a&&<div id="result"><div className="result-hero"><div><small>ANALYSIS / {new Date(item!.createdAt).toLocaleDateString('zh-CN')} · {a.mode==='agent'?'AI Agent':'规则引擎'}</small><h2>{a.title}</h2><p>{a.verdict}</p></div><div className="score"><strong>{a.score}%</strong><span>文本覆盖度</span></div></div><p className="method"><ShieldAlert size={16}/>{a.method}</p>{!!a.sources?.length&&<section className="panel result-panel"><h2>证据来源</h2><ul>{a.sources.map(source=><li key={source.id}>[{source.id}] {source.url?<a href={source.url} target="_blank" rel="noopener noreferrer">{source.source}</a>:source.source}</li>)}</ul></section>}
 <section className="panel result-panel"><div className="section-head"><div><h2>岗位要求拆解</h2><p>请逐条核对提取内容是否准确</p></div><span className="pill">{a.requirements.length} 项</span></div>{a.requirements.length?a.requirements.map((r,i)=><div className="requirement" key={i}><span className={'indicator '+(r.kind==='risk'?'risk':r.matched?'yes':'')}>{r.kind==='risk'?'!':r.matched?'✓':'—'}</span><div><div><span className={'tag '+r.kind}>{labels[r.kind]}</span> {r.text}</div><small>{r.kind==='risk'?'可能涉及硬性门槛或收费风险，请向招聘方核实':r.matched?r.evidence:'个人资料中暂未找到直接证据；不等于你一定不会'}</small></div></div>):<p className="muted">未识别出清晰要求。建议粘贴完整 JD。</p>}</section>
 <div className="two"><section className="panel result-panel"><div className="section-head"><div><h2>可展示的证据</h2><p>面试时打开作品并讲清自己的部分</p></div><Check size={18}/></div>{a.strengths.length?<ul>{a.strengths.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="muted">暂未找到明确交集。补充可验证的项目事实再试一次。</p>}</section><section className="panel result-panel"><div className="section-head"><div><h2>需要准备的缺口</h2><p>先核实，不把未知说成已掌握</p></div></div>{a.gaps.length?<ul>{a.gaps.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="muted">提取的要求均有文本交集，仍建议验证实际能力。</p>}</section></div>
 <section className="panel result-panel accent"><div className="section-head"><div><div className="kicker">READY TO EDIT</div><h2>给招聘方的开场白</h2><p>发送前检查岗位名称和事实，按你的语气修改</p></div><Button variant="outline" size="sm" onClick={copy}>{copied?<Check size={15}/>:<Clipboard size={15}/>} {copied?'已复制':'复制'}</Button></div><div className="message">{a.opener}</div></section><section className="panel result-panel"><div className="section-head"><div><h2>面试准备</h2><p>围绕事实、过程和演示来回答</p></div></div>{a.questions.map((q,i)=><div className="qa" key={i}><strong><em>Q{i+1}</em> {q.question}</strong><p>{q.answer}</p></div>)}</section></div>}
 <footer>JobHunter Agent v2 · AI Agent / 规则回退</footer></div></div></main>
}

